{% set version = "1.8.6" %}
{% set sha256 = "d113efa48d29d825eb47abd4ee5124b9b51d7062714a83fc49104552547d5584" %}

package:
  name: links
  version: {{ version }}

source:
  url: http://www.bcgsc.ca/platform/bioinfo/software/links/releases/{{ version }}/links_v{{ version | replace(".","-") }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True # [osx]

requirements:
  build:
    - perl
    - swig
    - {{ compiler('cxx') }}
  host:
    - perl
  run:
    - perl
test:
  commands:
    - LINKS  | grep 'Usage' > /dev/null

about:
  summary: Long Interval Nucleotide K-mer Scaffolder
  home: http://www.bcgsc.ca/platform/bioinfo/software/links
  license: GPLv3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
